
// INCLUDE THIS FILE IN YOUR MAKECALL.PHP SCRIPT TO BE ABLE TO USE CARRIER NAMES VARIABLES INSTEAD OF HAVING TO REMEMBER OR RETREIVE i
// THE I_CONNECTION ID FOR EACH CARRIER 

// CARRIER NAME | I_CONNECTION 

$TATA = 220; // ROUTES THE CALL TO TATA COMMUNICATIONS PRIME DIVISION
$VIBER = 1771; // ROUTES THE CALL TO VIBER ONNET NETWORK , PHONE NUMBER MUST BE ONLINE WITH VIBER APP TO RECEIVE THE CALL.
$IBASIS = 234; // ROUTES THE CALL VIA IBASIS PRIME NETWORK

// feel free to add your own sellers and connections , you can get seller i_connection from tcxc portal  
